name: Deploy Workflow1

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Show current branch
        run: echo "Running workflow1 on branch ${{ github.ref }}"
